"""eh, we don't need the logins relation just yet

Revision ID: 467e50eb48ea
Revises: 21f7c33730df
Create Date: 2013-01-10 23:04:29.297192

"""

# revision identifiers, used by Alembic.
revision = '467e50eb48ea'
down_revision = '21f7c33730df'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'logins')
    op.drop_table(u'passwordlogins')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=60), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'created_at')
    op.create_table('logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passwordlogins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['logins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
